### ISSUE TITLE
How would one save cache items?

### ISSUE THREAD

**Issue by Nyholm** [php-cache/doctrine-adapter#2]
The CacheItemInterface does not have a `getExpiration" function. How can the cache pool know how to save the cache item then?

Other libraries have introduces a `getTtl` or `getExpiration` functions on the cache item implementation. This is wrong because our implementation of the pool should be able to store other implementations of cache item. 

Is it something I'm missing or is this function missing on the PSR-6? Should I open a ticket at their repository?

**Comment by aequasi** [comment]
May be worth asking them, yeah

**Comment by aequasi** [comment]
`https://github.com/php-cache/doctrine-adapter/blob/master/src/CachePoolItem.php#L120`

That should be `$item->get()` for the value, btw

**Comment by Nyholm** [comment]
> That should be $item->get() for the value, btw

No, it should not. We store the `CacheItem` in the cache. That is an extra serialization but we need to have all that data in the cache. 


I'll ask them.

**Comment by aequasi** [comment]
Ah, yeah. Correct. We talked about that.

**Comment by Nyholm** [comment]
We introduce another interface. Closing this.
